TASK_KEY = "task"
TASK_LOGIC_RULE_GEN = "logic_llm_rule_gen"
TASK_IRAC_RENDER = "irac_render"

PAYLOAD_TRACE_KEY = "trace"
PAYLOAD_TRAINING_QUESTION_KEY = "training_question"
PAYLOAD_RETRIEVED_CHUNKS_KEY = "retrieved_chunks"
PAYLOAD_PREVIOUS_ERROR_KEY = "previous_error"
PAYLOAD_PREVIOUS_OUTPUT_KEY = "previous_output"
PAYLOAD_PREVIOUS_PROGRAM_KEY = "previous_program"
PAYLOAD_FEEDBACK_KEY = "feedback"

RESPONSE_TEXT_KEY = "text"
RESPONSE_ANSWER_KEY = "answer"
RESPONSE_LEGAL_SOURCES_KEY = "legal_sources"
RESPONSE_RULES_KEY = "rules"
RESPONSE_VERIFY_FACTS_KEY = "verify_facts"
RESPONSE_QUERY_KEY = "query"
RESPONSE_ANSWER_VAR_KEY = "answer_var"
RESPONSE_ANSWER_TYPE_KEY = "answer_type"
RESPONSE_PREDICATE_INPUTS_KEY = "predicate_inputs"
RESPONSE_CITATIONS_KEY = "citations"
RESPONSE_RAW_LLM_OUTPUT_KEY = "raw_llm_output"
RESPONSE_PREDICATE_KEY = "predicate"

ANSWER_TYPE_SCALAR = "scalar"
ANSWER_TYPE_EXPLAIN = "explain"
USER_ATOM = "user"
TRACE_VARIABLE_NAME = "Trace"

STATUS_UNABLE_TO_CONCLUDE = "unable_to_conclude"
STATUS_CITATION_REQUIRED = "citation_required"
STATUS_INVALID_PROGRAM = "invalid_program"
STATUS_INVALID_QUERY = "invalid_query"
STATUS_SYNTAX_ERROR = "syntax_error"
STATUS_DERIVED_FALSE = "derived_false"
STATUS_SUCCESS = "success"

FIELD_ID = "id"
FIELD_CHUNK_ID = "chunk_id"
FIELD_DOCUMENT = "document"
FIELD_ARTICLE = "article"
FIELD_CLAUSE = "clause"
FIELD_POINT = "point"
FIELD_TEXT = "text"
FIELD_CHUNKS = "chunks"
FIELD_SCORES = "scores"
FIELD_INDEX = "index"
FIELD_RAW_TEXT = "raw_text"
FIELD_NORMALIZED_QUESTION = "normalized_question"
FIELD_LEGAL_ISSUE = "legal_issue"
FIELD_DOMAIN_CONTEXT = "domain_context"
FIELD_SELECTED_FUNCTION = "selected_function"
FIELD_NAME = "name"
FIELD_DESCRIPTION = "description"
FIELD_SLOT_BINDINGS = "slot_bindings"
FIELD_FACTS = "facts"
FIELD_EXECUTION_RESULT = "execution_result"
FIELD_PROLOG_TRACE = "prolog_trace"
FIELD_GENERATED_PROGRAM = "generated_program"
FIELD_QUESTION = "question"
FIELD_RETRIEVED_CHUNKS = "retrieved_chunks"
FIELD_PROGRAM = "program"
FIELD_VERIFICATION = "verification"
FIELD_SUCCESS = "success"
FIELD_STATUS = "status"
FIELD_ERROR = "error"
FIELD_RESULT = "result"
FIELD_SOLUTIONS = "solutions"
FIELD_RENDER_PAYLOAD = "render_payload"
FIELD_RENDERED_ANSWER = "rendered_answer"
FIELD_PROLOG_SOURCE = "prolog_source"

RAW_PROGRAM_TEXT_ATTRIBUTE = "raw_program_text"
CITATION_INDICES_ATTRIBUTE = "citation_indices"
PREDICATE_FACT_PREFIX_TEMPLATE = "{predicate}("

DOMAIN_CONTEXT = "Vietnamese social insurance legal QA"
SELECTED_FUNCTION_NAME = "one-shot generated Prolog program"
SELECTED_FUNCTION_DESCRIPTION = (
    "Generated from the user question and retrieved legal sources."
)
