DEFAULT_RETRIEVAL_TOP_K_IN_CODE = 5
RETRIEVAL_INNER_K_MULTIPLIER = 3
RETRIEVAL_MODE_ONTOLOGY = "ontology"
RETRIEVAL_MODE_HYBRID = "hybrid"
DEFAULT_RETRIEVAL_MODE = RETRIEVAL_MODE_ONTOLOGY

ONTOLOGY_CONCEPT_MATCH_WEIGHT = 3.0
ONTOLOGY_THRESHOLD_MATCH_WEIGHT = 2.0
ONTOLOGY_LEGAL_REF_MATCH_WEIGHT = 2.5
ONTOLOGY_DOCUMENT_MATCH_WEIGHT = 5.0
ONTOLOGY_KEYWORD_MATCH_WEIGHT = 1.0
ONTOLOGY_ARTICLE_EXPANSION_WEIGHT = 0.25

ERROR_RETRIEVAL_WEIGHTS_NON_NEGATIVE = "retrieval weights must be non-negative"
ERROR_RETRIEVAL_WEIGHT_SUM_POSITIVE = (
    "at least one retrieval weight must be positive"
)
ERROR_INVALID_JSONL_TEMPLATE = "invalid JSONL at line {line_number}: {error}"
ERROR_DUPLICATE_CORPUS_ID_TEMPLATE = (
    "duplicate corpus id at line {line_number}: {chunk_id}"
)
ERROR_MISSING_CORPUS_FIELD_TEMPLATE = "missing {field} at line {line_number}"
ERROR_EMPTY_CORPUS_FIELD_TEMPLATE = "empty {field} at line {line_number}"
